# Generated by Django 5.1.2 on 2025-07-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_doctor_userprofile_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='revenue_share',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
