# Generated by Django 5.1.2 on 2025-07-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_doctor_revenue_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('assistant', 'Assistant'), ('manager', 'Manager')], max_length=20, null=True),
        ),
    ]
