# Generated by Django 5.1.2 on 2025-08-06 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_doctor_user'),
        ('appointment', '0001_initial'),
        ('patients', '0007_alter_patient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True, null=True)),
                ('medical_advice', models.TextField(blank=True, null=True)),
                ('planned_procedures', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appointment')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinical_exams', to='patients.patient')),
            ],
        ),
    ]
