# Generated by Django 5.1.2 on 2025-08-07 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalexam',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_exam', to='appointment.appointment'),
        ),
    ]
