# Generated by Django 5.1.2 on 2025-08-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_doctor_user'),
        ('procedures', '0003_alter_clinicalexam_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dental Procedure (Definition)',
                'verbose_name_plural': 'Dental Procedures (Definitions)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='procedures.clinicalexam')),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='performed', to='procedures.dentalprocedure')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_procedures', to='procedures.procedurecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dentalprocedure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='definitions', to='procedures.procedurecategory'),
        ),
        migrations.CreateModel(
            name='Toothcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tooth_number', models.CharField(db_index=True, max_length=10)),
                ('tooth_type', models.CharField(choices=[('permanent', 'Permanent'), ('primary', 'Primary')], default='permanent', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['tooth_type', 'tooth_number'],
                'indexes': [models.Index(fields=['tooth_number', 'tooth_type'], name='procedures__tooth_n_7bf896_idx')],
                'unique_together': {('tooth_number', 'tooth_type')},
            },
        ),
        migrations.CreateModel(
            name='ProcedureToothcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tooth_links', to='procedures.procedure')),
                ('toothcode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_links', to='procedures.toothcode')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['clinical_exam'], name='procedures__clinica_cb22e6_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['created_at'], name='procedures__created_8808cb_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduretoothcode',
            index=models.Index(fields=['procedure'], name='procedures__procedu_e9fb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduretoothcode',
            index=models.Index(fields=['toothcode'], name='procedures__toothco_3d3f2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='proceduretoothcode',
            unique_together={('procedure', 'toothcode')},
        ),
    ]
