# Generated by Django 5.1.2 on 2025-08-11 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0004_dentalprocedure_procedurecategory_procedure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalexam',
            name='planned_procedures',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_exams', to='procedures.dentalprocedure'),
        ),
    ]
