# Generated by Django 5.1.2 on 2025-08-11 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0005_alter_clinicalexam_planned_procedures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicalexam',
            old_name='planned_procedures',
            new_name='planned_procedures_text',
        ),
    ]
