# Generated by Django 5.1.2 on 2025-08-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0006_rename_planned_procedures_clinicalexam_planned_procedures_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalexam',
            name='planned_procedures',
            field=models.ManyToManyField(blank=True, related_name='planned_exams', to='procedures.dentalprocedure'),
        ),
        migrations.AlterField(
            model_name='clinicalexam',
            name='planned_procedures_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
