# Generated by Django 5.1.2 on 2025-08-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0007_clinicalexam_planned_procedures_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalexam',
            name='planned_procedures_text',
        ),
    ]
