# Generated by Django 5.1.2 on 2025-08-12 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0009_remove_clinicalexam_planned_procedures_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicalexam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clinical Exam', 'verbose_name_plural': 'Clinical Exams'},
        ),
    ]
