# Generated by Django 5.1.2 on 2025-08-15 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0010_alter_clinicalexam_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentalprocedure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='procedures.procedurecategory'),
        ),
    ]
