# Generated by Django 5.1.2 on 2025-08-19 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0011_alter_dentalprocedure_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicalexam',
            name='planned_procedures',
        ),
    ]
