# Generated by Django 5.1.2 on 2025-08-19 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_doctor_user'),
        ('procedures', '0012_remove_clinicalexam_planned_procedures'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalExamItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinical_exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='procedures.clinicalexam', verbose_name='Clinical Exam')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_exam_items', to='accounts.doctor', verbose_name='Performed By')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_exam_items', to='procedures.dentalprocedure', verbose_name='Procedure')),
                ('toothcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_exam_items', to='procedures.toothcode', verbose_name='Tooth')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['clinical_exam'], name='procedures__clinica_2bbff5_idx'), models.Index(fields=['procedure'], name='procedures__procedu_8d3b84_idx'), models.Index(fields=['toothcode'], name='procedures__toothco_e95704_idx')],
                'constraints': [models.UniqueConstraint(fields=('clinical_exam', 'procedure', 'toothcode'), name='uniq_exam_proc_tooth')],
            },
        ),
    ]
