# Generated by Django 5.1.2 on 2025-08-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedures', '0013_clinicalexamitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalexam',
            name='prescription_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Prescription Notes'),
        ),
    ]
