upstream django_app {
    # اسم الخدمة في docker-compose هو web، والبورت الداخلي لـ gunicorn هو 8000
    server web:8000;
}

server {
    listen 80;
    # ضع هنا الآي بي الخاص بـ AWS أو الـ Domain الخاص بك لاحقاً
    server_name localhost 13.60.214.220; 

    # زيادة حجم الملفات المسموح برفعها (مهم لصور عيادات الأسنان والأشعة)
    client_max_body_size 50M;

    # تعطيل إظهار إصدار Nginx في أخطاء السيرفر لحماية النظام من الثغرات
    server_tokens off;

    # الملفات الثابتة (Static Files)
    location /static/ {
        alias /app/staticfiles/;
        expires 30d; # كاش للمتصفح لمدة 30 يوم لزيادة السرعة
        add_header Cache-Control "public, no-transform";
    }

    # ملفات الميديا (Media Files)
    location /media/ {
        alias /app/media/;
        expires 30d;
    }

    # توجيه باقي الطلبات إلى حاوية Django
    location / {
        proxy_pass http://django_app;
        
        # تمرير قيم الـ Headers الحقيقية لـ Django ليعرف الآي بي الحقيقي للمستخدم
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
}