# Generated by Django 5.1.2 on 2025-08-06 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_doctor_user'),
        ('medicalrecord', '0001_initial'),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescribedmedication',
            name='clinical_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='procedures.clinicalexam'),
        ),
        migrations.AddField(
            model_name='prescribedmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medicalrecord.medication'),
        ),
        migrations.AddField(
            model_name='prescribedmedication',
            name='prescribed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor'),
        ),
    ]
