# Generated by Django 5.1.2 on 2025-08-07 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecord', '0002_initial'),
        ('procedures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedication',
            name='clinical_exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='procedures.clinicalexam'),
        ),
    ]
