# Generated by Django 5.1.2 on 2025-08-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecord', '0003_alter_prescribedmedication_clinical_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChronicDisease',
        ),
    ]
