# Generated by Django 5.1.2 on 2025-08-17 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecord', '0004_delete_chronicdisease'),
        ('procedures', '0011_alter_dentalprocedure_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['name'], 'verbose_name': 'Medication', 'verbose_name_plural': 'Medications'},
        ),
        migrations.AlterField(
            model_name='medication',
            name='default_dose_unit',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Default Dose Unit'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Medication Name'),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='clinical_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='procedures.clinicalexam'),
        ),
    ]
