# Generated by Django 5.1.2 on 2025-08-17 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_doctor_user'),
        ('medicalrecord', '0005_alter_medication_options_and_more'),
        ('procedures', '0011_alter_dentalprocedure_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescribedmedication',
            name='clinical_exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed_medications', to='procedures.clinicalexam', verbose_name='Clinical Exam'),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='dose_unit',
            field=models.CharField(max_length=50, verbose_name='Dose Unit'),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='medicalrecord.medication', verbose_name='Medication'),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='number_of_days',
            field=models.PositiveIntegerField(verbose_name='Number Of Days'),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='prescribed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Prescribed At'),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='prescribed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor', verbose_name='Prescribed By'),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='times_per_day',
            field=models.PositiveIntegerField(verbose_name='Times Per Day'),
        ),
    ]
