# Generated by Django 5.1.2 on 2025-08-18 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecord', '0007_appliedmedicationpackage_medicationpackage_and_more'),
        ('patients', '0008_alter_patient_options_disease_medication_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicationpackageitem',
            name='mpi_times_per_day_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='medicationpackageitem',
            name='mpi_number_of_days_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='prescribedmedication',
            name='pm_times_per_day_gt_0',
        ),
        migrations.RemoveConstraint(
            model_name='prescribedmedication',
            name='pm_number_of_days_gt_0',
        ),
        migrations.AlterField(
            model_name='medicationpackage',
            name='disease',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medication_packages', to='patients.disease', verbose_name='Disease'),
        ),
        migrations.AlterField(
            model_name='medicationpackageitem',
            name='number_of_days',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Number Of Days'),
        ),
        migrations.AlterField(
            model_name='medicationpackageitem',
            name='times_per_day',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Times Per Day'),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='number_of_days',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Number Of Days'),
        ),
        migrations.AlterField(
            model_name='prescribedmedication',
            name='times_per_day',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Times Per Day'),
        ),
    ]
