# Generated by Django 5.1.2 on 2025-08-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicalrecord', '0008_remove_medicationpackageitem_mpi_times_per_day_gt_0_and_more'),
        ('patients', '0008_alter_patient_options_disease_medication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientPrescriptionReport',
            fields=[
            ],
            options={
                'verbose_name': 'تقرير وصفات المريض',
                'verbose_name_plural': 'تقارير وصفات المرضى',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('patients.patient',),
        ),
    ]
