# Generated by Django 5.1.2 on 2025-07-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'انثى')], max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
