# Generated by Django 5.1.2 on 2025-08-09 23:18

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Disease Name')),
                ('dental_impact', models.TextField(blank=True, null=True, verbose_name='Dental Impact')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Chronic Disease',
                'verbose_name_plural': 'Chronic Diseases',
                'ordering': ['name'],
                'indexes': [models.Index(django.db.models.functions.text.Lower('name'), name='idx_disease_name_ci'), models.Index(fields=['is_active'], name='patients_di_is_acti_891a42_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_disease_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Medication Name')),
                ('dental_impact', models.TextField(blank=True, null=True, verbose_name='Dental Impact')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
                'ordering': ['name'],
                'indexes': [models.Index(django.db.models.functions.text.Lower('name'), name='idx_medication_name_ci'), models.Index(fields=['is_active'], name='patients_me_is_acti_fa8bde_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_medication_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='PatientAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergic_reaction', models.TextField(blank=True, null=True, verbose_name='Allergic Reaction')),
                ('diagnosed_at', models.DateField(blank=True, null=True, verbose_name='Diagnosed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_allergy_links', to='patients.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_allergies', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Allergy',
                'verbose_name_plural': 'Patient Allergies',
                'db_table': 'PATIENT_ALLERGIES',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='patients', through='patients.PatientAllergy', to='patients.medication', verbose_name='Drug Allergies'),
        ),
        migrations.CreateModel(
            name='PatientDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosed_at', models.DateField(blank=True, null=True, verbose_name='Diagnosed At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_disease_links', to='patients.disease')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diseases', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Disease',
                'verbose_name_plural': 'Patient Diseases',
                'db_table': 'PATIENT_DISEASES',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='diseases',
            field=models.ManyToManyField(blank=True, related_name='patients', through='patients.PatientDisease', to='patients.disease', verbose_name='Chronic Diseases'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['first_name', 'last_name'], name='patients_pa_first_n_a142c0_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['email'], name='patients_pa_email_bb026d_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_archived'], name='patients_pa_is_arch_b8e241_idx'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['patient'], name='PATIENT_ALL_patient_1b9949_idx'),
        ),
        migrations.AddIndex(
            model_name='patientallergy',
            index=models.Index(fields=['medication'], name='PATIENT_ALL_medicat_5944f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientallergy',
            constraint=models.UniqueConstraint(fields=('patient', 'medication'), name='uniq_patient_medication'),
        ),
        migrations.AddIndex(
            model_name='patientdisease',
            index=models.Index(fields=['patient'], name='PATIENT_DIS_patient_0523f1_idx'),
        ),
        migrations.AddIndex(
            model_name='patientdisease',
            index=models.Index(fields=['disease'], name='PATIENT_DIS_disease_2697fb_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientdisease',
            constraint=models.UniqueConstraint(fields=('patient', 'disease'), name='uniq_patient_disease'),
        ),
    ]
