# Generated by Django 5.1.2 on 2026-06-18 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clinic_customuser_clinic'),
        ('patients', '0008_alter_patient_options_disease_medication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.clinic'),
        ),
    ]
